### ISSUE TITLE
Users can add additional information about the brewery with Open Brewery DB

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/ajax-project#4]
### Motivation
User wants to be able to add brewery info about their beer.

### Plan
Create a dropdown menu showing a list of matches produced by the API.

### Task List
- [x] Add a 'click' event listener to the search button.

- [x] Create a dropdown menu  on the search button in HTML.

- [x] Make the drop-menu look polished.

- [x] Create a function for creating that menu as a DOM tree.

- [x] Alter the click event listener to open the menu

- [x] Add functionality so that if the user clicks off the menu, it goes away.

- [x] Define a function that queries the API for the value of the brewery input box, and returns a list of the first three matches.

- [x] Alter the getDropdownMenu function to create a DOM tree for up to three matches.

- [x] Append those matches to the menu.

- [x] Add an event listener to each match in the submenu.

- [x] Add a function to the event listener so that if a match is clicked, selected data is saved to an object.

- [x] Alter the getBeerObjectInDOM function so that if brewery info is submitted, it is added to the DOM tree for a beer entry.

- [x] Squash all bugs.
