### ISSUE TITLE
Users can remove beer from their ‘cellars’

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/ajax-project#5]
### Motivation
--
Users will want to be able to delete entries that are no longer relevant.

### Plan
--
Create a button that deletes an entry from view AND local storage.

### Task List
--

- [x] Create a button in html

- [x] Make the button look nice.

- [x] Alter the getBeerEntryInDOM function to add the button to the correct place in each entry.

- [x] Add an event listener to the button

- [x] Add a function to the event listener that removes the element from the DOM.

- [x] Enhance the functionality of that function to also update local storage.

- [x] Final CSS polish.

- [x] Squish all bugs
